### ISSUE TITLE
RichTextRenderer not respecting v-show 

### ISSUE THREAD

**Issue by fanckush** [MarvinRudolph/storyblok-rich-text-renderer#19]
Hey again,
It's possible this is caused by other factors but the following code doesn't work: 

``` vue
<RichTextRenderer
  v-show="false"
  :document="theDoc"
/>
```

while this works: 
``` vue
<div v-show="false">
  <RichTextRenderer  :document="theDoc"  />
</div>
```

and this works too:
``` vue
<RichTextRenderer
  v-if="false"
  :document="theDoc"
/>
```

I'm using V3.2

**Edit**
maybe related https://github.com/vuejs/vue/issues/1388

**Comment by MarvinRudolph** [comment]
Hey! The console shows 
<img width="831" alt="CleanShot 2022-01-20 at 13 33 55@2x" src="https://user-images.githubusercontent.com/6840287/150339559-f7fa95df-2410-420f-8318-3019b3fc744e.png">
which is because the component doesn't have a root node but renders the content as fragments. 

You can either do it like you already do it (with a separate div) or you could change the resolver of `NodeTypes.DOCUMENT`. Currently, it renders just the children but you could modify it to something like `({ children }) => h('div', children)`. This ensures that it renders the content of the rich text always inside a `<div>`. 

In Vue 2 it was always there because fragments weren't allowed.

**Comment by fanckush** [comment]
Aaah that makes sense. Thanks for the clarification
